### PR TITLE
Logout side drawer button added with functioning

### PR DESCRIPTION
**Pull request by Priya-Mohod**
Worked on Logout function
1. Logout button created
2. Added dialogue box

### CODE REVIEW

**Review by Priya-Mohod — COMMENTED** [review]
File names updated

**Review by tushmohod — APPROVED** [review]
Approved

**Comment by tushmohod** [comment]
In near future we need to move this code LoginViewModel to maintain user logout functionality.

**Review by Priya-Mohod — COMMENTED** [review]
file names updated

**Pull request merged**
